/**
 * MyApi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { User } from './user';
import { Product } from './product';


export interface Sale { 
    id?: number;
    userId?: number;
    user?: User;
    productId?: number;
    product?: Product;
    quantity?: number;
}

